### ISSUE TITLE
If I don't type area name in gVI I will get IndexOutOfRangeException

### ISSUE THREAD

**Issue by ToliaFolia** [EZombian/blind-os#12]
Version 1.0-pre1 and older

**Comment by EZombian** [comment]
**Fixing this bug will require gVI to be redesigned. This may take more time. We will reopen your thread when we start to fix your bug.**

**Comment by EZombian** [comment]
_I started fixing your bug._

**Comment by EZombian** [comment]
Fixed 👍 It will added in patch-4
