### ISSUE TITLE
Files "BlindOS.exe" in obj/Debug and bin/Debug was not updated in 1.0

### ISSUE THREAD

**Issue by ToliaFolia** [EZombian/blind-os#13]
These files wasn't updated in last relase

**Comment by EZombian** [comment]
Oops, our mistake 😕 . We'll add this to patch-5 (we'll do it right away)

**Comment by EZombian** [comment]
Only the obj/Debug folder will be updated

**Comment by EZombian** [comment]
Fixed 👍
